apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-container
        image: europe-west1-docker.pkg.dev/qwiklabs-gcp-02-3069e1a4af2c/my-repository/hello-cloudbuild-dev:v1.0
        ports:
        - containerPort: 8080
